[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1e2124"
foreground = "#00ff00"

[colors.cursor]
text = "CellBackground"
cursor = "#528bff"

[colors.normal]
black = "#21222c"
blue = "#0bbecc"
cyan = "#0088aa"
green = "#50fa7b"
magenta = "#b271a9"
red = "#ff5555"
white = "#f8f8f2"
yellow = "#f1fa8c"

[colors.bright]
black = "#6272a4"
red = "#ff6e6e"
green = "#69ff94"
yellow = "#ffffa5"
blue = "#d6acff"
magenta = "#ff92df"
cyan = "#a4ffff"
white = "#ffffff"

[colors.selection]
text = "CellForeground"
background = "#3e4451"
